dependencies:
 - python=3.6
 - requests
 - pip:
   - pytest 
   - beautifulsoup4
   - google
   - langdetect
   - pyqt5==5.11.2 
   - tldextract
   - jsonpickle
   - google-api-python-client
   - oauth2client