BASE_INFO = 'data/interim/song_data.json'
TRANSLATION = 'data/processed/translation.txt'
ORIGINAL = 'data/processed/original.txt'
CONTENT = 'data/processed/editor_content.json'
FINAL_CONTENT = 'data/processed/final_content.json'
OTHER_DATA = 'src/resources/other_data.json'